# Generated by Django 5.2.7 on 2025-11-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('pubkey_pem', models.TextField()),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=128, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='devices_dev_name_7c6eed_idx'), models.Index(fields=['is_active'], name='devices_dev_is_acti_52b321_idx'), models.Index(fields=['location'], name='devices_dev_locatio_c16132_idx'), models.Index(fields=['last_seen'], name='devices_dev_last_se_66ef2a_idx')],
            },
        ),
    ]
