# Generated by Django 5.2.7 on 2025-10-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='location',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['name'], name='devices_dev_name_7c6eed_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['is_active'], name='devices_dev_is_acti_52b321_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['location'], name='devices_dev_locatio_c16132_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['last_seen'], name='devices_dev_last_se_66ef2a_idx'),
        ),
    ]
