# Generated by Django 5.2.7 on 2025-11-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Uncheck to disable this device's rules / ingestion without deleting it."),
        ),
    ]
