# Generated by Django 5.2.7 on 2025-10-31 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_description_device_last_seen_device_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
