# Generated by Django 5.2.7 on 2025-11-06 13:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPointWhitelistGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Friendly name, e.g. 'Ward 3A Wi-Fi'", max_length=128)),
                ('ssid', models.CharField(db_index=True, max_length=64)),
                ('location', models.CharField(blank=True, help_text='Floor / ward / building', max_length=128, null=True)),
                ('default_security', models.CharField(blank=True, help_text='Expected security for this SSID, e.g. WPA2-PSK', max_length=64, null=True)),
                ('strict', models.BooleanField(default=False, help_text='If True, ONLY entries under this group are accepted for this SSID.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AP Whitelist Group',
                'verbose_name_plural': 'AP Whitelist Groups',
            },
        ),
        migrations.CreateModel(
            name='AccessPointWhitelistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bssid', models.CharField(blank=True, db_index=True, help_text='Exact AP MAC, e.g. AA:BB:CC:DD:EE:FF. Leave empty to allow any BSSID under this SSID.', max_length=17, null=True)),
                ('security', models.CharField(blank=True, help_text="Expected security (compared to ESP32 'security' field).", max_length=64, null=True)),
                ('channel', models.IntegerField(blank=True, help_text='Expected channel for this AP. Leave blank to ignore.', null=True)),
                ('vendor_oui', models.CharField(blank=True, help_text="OUI prefix, e.g. 'F09FC2' (optional, from BSSID).", max_length=8, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='evidence.accesspointwhitelistgroup')),
            ],
            options={
                'verbose_name': 'AP Whitelist Entry',
                'verbose_name_plural': 'AP Whitelist Entries',
            },
        ),
        migrations.CreateModel(
            name='AccessPointObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.CharField(blank=True, max_length=64, null=True)),
                ('bssid', models.CharField(db_index=True, max_length=17)),
                ('oui', models.CharField(blank=True, help_text="First 3 bytes of BSSID, as hex (e.g. 'F09FC2').", max_length=8, null=True)),
                ('channel', models.PositiveIntegerField(default=1, help_text='Wi-Fi channel (1–196)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(196)])),
                ('band', models.CharField(blank=True, help_text='Optional band label, e.g. 2.4GHz / 5GHz / 6GHz.', max_length=16, null=True)),
                ('rssi_current', models.IntegerField(blank=True, help_text='Current RSSI (from ESP32: rssi_cur)', null=True)),
                ('rssi_best', models.IntegerField(blank=True, help_text='Best RSSI seen (from ESP32: rssi_best)', null=True)),
                ('beacons', models.IntegerField(blank=True, help_text='Number of beacons seen for this BSSID', null=True)),
                ('sensor_last_seen_ms', models.BigIntegerField(blank=True, help_text="ESP32 'last_seen_ms' (millis since start of capture).", null=True)),
                ('security', models.CharField(blank=True, help_text='Security type detected by ESP32, e.g. WPA2-PSK, Open, WPA3-SAE', max_length=64, null=True)),
                ('rsn_text', models.CharField(blank=True, help_text="RSN column from ESP32, e.g. 'CCMP/CCMP' or '-'", max_length=128, null=True)),
                ('akm_list', models.CharField(blank=True, help_text="Comma-separated AKMs from ESP32, e.g. 'PSK,SAE'", max_length=256, null=True)),
                ('pmf_capable', models.BooleanField(default=False)),
                ('pmf_required', models.BooleanField(default=False)),
                ('canonical', models.TextField(blank=True, help_text='Exact canonical string that the ESP32 signed.', null=True)),
                ('hash_sha256', models.CharField(blank=True, help_text='SHA-256 hex digest of canonical string, from ESP32.', max_length=64, null=True)),
                ('sig_alg', models.CharField(blank=True, help_text="Signature algorithm, e.g. 'ECDSA_P256_SHA256'.", max_length=64, null=True)),
                ('sig_r', models.CharField(blank=True, max_length=80, null=True)),
                ('sig_s', models.CharField(blank=True, max_length=80, null=True)),
                ('sensor_ts', models.DateTimeField(blank=True, help_text='Device-reported timestamp (if you later send real UTC).', null=True)),
                ('server_ts', models.DateTimeField(default=django.utils.timezone.now, help_text='Server ingest timestamp')),
                ('match_status', models.CharField(blank=True, help_text='WHITELISTED_STRONG / WHITELISTED_WEAK / KNOWN_SSID_BUT_UNEXPECTED_AP / UNREGISTERED_AP', max_length=64, null=True)),
                ('similarity_score', models.FloatField(default=0.0, help_text='0–1 similarity to expected SSID (optional, can compute in view).')),
                ('risk_score', models.FloatField(default=0.0, help_text='0–100 computed risk score.')),
                ('flags', models.JSONField(default=list, help_text="List of triggered alert flags, e.g. ['UNREGISTERED_AP', 'DOWNGRADED_SECURITY']")),
                ('is_flagged', models.BooleanField(default=False, help_text='Set True if this observation should alert on dashboard.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(blank=True, help_text='Originating scanner / device', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ap_observations', to='devices.device')),
                ('matched_entry', models.ForeignKey(blank=True, help_text='Which specific entry (BSSID/security) matched.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_observations', to='evidence.accesspointwhitelistentry')),
                ('matched_group', models.ForeignKey(blank=True, help_text='Which whitelist group matched this observation (by SSID).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_observations', to='evidence.accesspointwhitelistgroup')),
            ],
            options={
                'verbose_name': 'Access Point Observation',
                'verbose_name_plural': 'Access Point Observations',
                'indexes': [models.Index(fields=['ssid'], name='evidence_ac_ssid_5105fe_idx'), models.Index(fields=['bssid'], name='evidence_ac_bssid_18c5e6_idx'), models.Index(fields=['server_ts'], name='evidence_ac_server__30f17b_idx'), models.Index(fields=['device'], name='evidence_ac_device__412ebb_idx')],
            },
        ),
    ]
