# Generated by Django 5.2.7 on 2025-11-14 23:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPointWhitelistGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Friendly name, e.g. 'Ward 3A Wi-Fi'", max_length=128)),
                ('ssid', models.CharField(db_index=True, max_length=64)),
                ('location', models.CharField(blank=True, help_text='Floor / ward / building', max_length=128, null=True)),
                ('default_security', models.CharField(blank=True, help_text='Expected security for this SSID, e.g. WPA2-PSK', max_length=64, null=True)),
                ('strict', models.BooleanField(default=False, help_text='If True, ONLY entries under this group are accepted for this SSID.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to temporarily disable this whitelist group.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AP Whitelist Group',
                'verbose_name_plural': 'AP Whitelist Groups',
                'indexes': [models.Index(fields=['ssid'], name='evidence_ac_ssid_3b475c_idx'), models.Index(fields=['is_active'], name='evidence_ac_is_acti_89a5cd_idx')],
            },
        ),
        migrations.CreateModel(
            name='AccessPointWhitelistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bssid', models.CharField(blank=True, db_index=True, help_text='Exact AP MAC, e.g. AA:BB:CC:DD:EE:FF. Leave empty to allow any BSSID under this SSID.', max_length=17, null=True)),
                ('security', models.CharField(blank=True, help_text="Expected security (compared to ESP32 'security' field), e.g. WPA2-PSK.", max_length=64, null=True)),
                ('channel', models.IntegerField(blank=True, help_text='Expected channel for this AP. Leave blank to ignore.', null=True)),
                ('band', models.CharField(blank=True, help_text="Expected band label, e.g. '2.4GHz', '5GHz', '6GHz' (optional).", max_length=16, null=True)),
                ('vendor_oui', models.CharField(blank=True, help_text="Expected OUI prefix, e.g. 'F09FC2' (optional, from BSSID).", max_length=8, null=True)),
                ('rsn_text', models.CharField(blank=True, help_text="Expected RSN text, e.g. 'CCMP/CCMP'. Leave blank to ignore.", max_length=128, null=True)),
                ('akm_list', models.CharField(blank=True, help_text="Expected AKM list, e.g. 'PSK,SAE'. Leave blank to ignore.", max_length=256, null=True)),
                ('pmf_capable', models.BooleanField(default=False, help_text='Check if AP is expected to advertise PMF capable. Leave default if not used.')),
                ('pmf_required', models.BooleanField(default=False, help_text='Check if AP is expected to require PMF. Leave default if not used.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to disable this exact AP entry without deleting it.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='evidence.accesspointwhitelistgroup')),
            ],
            options={
                'verbose_name': 'AP Whitelist Entry',
                'verbose_name_plural': 'AP Whitelist Entries',
            },
        ),
        migrations.CreateModel(
            name='AccessPointObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.CharField(blank=True, max_length=64, null=True)),
                ('bssid', models.CharField(db_index=True, max_length=17)),
                ('oui', models.CharField(blank=True, help_text="First 3 bytes of BSSID, as hex (e.g. 'F09FC2').", max_length=8, null=True)),
                ('channel', models.PositiveIntegerField(default=1, help_text='Wi-Fi channel (1–196)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(196)])),
                ('band', models.CharField(blank=True, help_text='Optional band label, e.g. 2.4GHz / 5GHz / 6GHz.', max_length=16, null=True)),
                ('rssi_current', models.IntegerField(blank=True, help_text='Current RSSI (from ESP32: rssi_cur)', null=True)),
                ('rssi_best', models.IntegerField(blank=True, help_text='Best RSSI seen (from ESP32: rssi_best)', null=True)),
                ('beacons', models.IntegerField(blank=True, help_text='Number of beacons seen for this BSSID', null=True)),
                ('sensor_last_seen_ms', models.BigIntegerField(blank=True, help_text="ESP32 'last_seen_ms' (millis since start of capture).", null=True)),
                ('security', models.CharField(blank=True, help_text='Security type detected by ESP32, e.g. WPA2-PSK, Open, WPA3-SAE', max_length=64, null=True)),
                ('rsn_text', models.CharField(blank=True, help_text="RSN column from ESP32, e.g. 'CCMP/CCMP' or '-'", max_length=128, null=True)),
                ('akm_list', models.CharField(blank=True, help_text="Comma-separated AKMs from ESP32, e.g. 'PSK,SAE'", max_length=256, null=True)),
                ('pmf_capable', models.BooleanField(default=False)),
                ('pmf_required', models.BooleanField(default=False)),
                ('canonical', models.TextField(blank=True, help_text='Exact canonical string that the ESP32 signed.', null=True)),
                ('hash_sha256', models.CharField(blank=True, help_text='SHA-256 hex digest of the canonical string (device-sent).', max_length=64, null=True)),
                ('sig_alg', models.CharField(blank=True, help_text="Signature algorithm, e.g. 'ECDSA_P256_SHA256'.", max_length=64, null=True)),
                ('sig_r', models.CharField(blank=True, max_length=130, null=True)),
                ('sig_s', models.CharField(blank=True, max_length=130, null=True)),
                ('sensor_ts', models.DateTimeField(blank=True, help_text='Device-reported timestamp (if you later send real UTC).', null=True)),
                ('server_ts', models.DateTimeField(default=django.utils.timezone.now, help_text='Server ingest timestamp')),
                ('match_status', models.CharField(blank=True, help_text='Snapshot status at ingest. Possible values include: WHITELISTED_STRONG, WHITELISTED_WEAK, CHANNEL_MISMATCH, SECURITY_MISMATCH, VENDOR_MISMATCH, BAND_MISMATCH, RSN_MISMATCH, AKM_MISMATCH, PMF_MISMATCH, KNOWN_SSID_BUT_UNEXPECTED_AP, KNOWN_SSID_REJECTED, UNREGISTERED_AP.', max_length=64, null=True)),
                ('similarity_score', models.FloatField(default=0.0)),
                ('risk_score', models.FloatField(default=0.0)),
                ('flags', models.JSONField(default=list, help_text="List of triggered alert flags, e.g. ['UNREGISTERED_AP']")),
                ('is_flagged', models.BooleanField(default=False, help_text='Set True if this observation should alert on dashboard.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prev_chain_hash', models.BinaryField(blank=True, help_text='Hash of previous observation for this device', null=True)),
                ('chain_hash', models.BinaryField(blank=True, help_text='Hash linking previous chain to this observation', null=True)),
                ('integrity_ok', models.BooleanField(default=True, help_text='Set False if later verification fails')),
                ('device', models.ForeignKey(blank=True, help_text='Originating scanner / device', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ap_observations', to='devices.device')),
                ('matched_entry', models.ForeignKey(blank=True, help_text='Which specific entry (BSSID/security) matched.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_observations', to='evidence.accesspointwhitelistentry')),
                ('matched_group', models.ForeignKey(blank=True, help_text='Which whitelist group matched this observation (by SSID).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_observations', to='evidence.accesspointwhitelistgroup')),
            ],
            options={
                'verbose_name': 'Access Point Observation',
                'verbose_name_plural': 'Access Point Observations',
            },
        ),
        migrations.CreateModel(
            name='UnregisteredAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.CharField(blank=True, max_length=64)),
                ('bssid', models.CharField(blank=True, db_index=True, help_text='AP MAC if known, otherwise empty for SSID-only entries.', max_length=17)),
                ('oui', models.CharField(blank=True, help_text="First 3 bytes of BSSID, as hex (e.g. 'F09FC2').", max_length=8)),
                ('channel', models.IntegerField(blank=True, help_text='Most recently seen channel for this AP.', null=True)),
                ('first_seen', models.DateTimeField(help_text='When this unregistered AP was first seen.')),
                ('last_seen', models.DateTimeField(help_text='When this unregistered AP was last seen.')),
                ('seen_count', models.PositiveIntegerField(default=0, help_text="How many times we've seen it.")),
                ('is_active', models.BooleanField(default=True, help_text='Active = still of interest; False = acknowledged / suppressed.')),
                ('notes', models.TextField(blank=True, help_text='Operator notes / investigation outcome.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_device', models.ForeignKey(blank=True, help_text='Last device that saw this AP.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unregistered_aps_last_seen', to='devices.device')),
            ],
            options={
                'verbose_name': 'Unregistered AP',
                'verbose_name_plural': 'Unregistered APs',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.AddIndex(
            model_name='accesspointwhitelistentry',
            index=models.Index(fields=['bssid'], name='evidence_ac_bssid_6690d4_idx'),
        ),
        migrations.AddIndex(
            model_name='accesspointwhitelistentry',
            index=models.Index(fields=['is_active'], name='evidence_ac_is_acti_c6747e_idx'),
        ),
        migrations.AddIndex(
            model_name='accesspointobservation',
            index=models.Index(fields=['ssid'], name='evidence_ac_ssid_5105fe_idx'),
        ),
        migrations.AddIndex(
            model_name='accesspointobservation',
            index=models.Index(fields=['bssid'], name='evidence_ac_bssid_18c5e6_idx'),
        ),
        migrations.AddIndex(
            model_name='accesspointobservation',
            index=models.Index(fields=['server_ts'], name='evidence_ac_server__30f17b_idx'),
        ),
        migrations.AddIndex(
            model_name='accesspointobservation',
            index=models.Index(fields=['device'], name='evidence_ac_device__412ebb_idx'),
        ),
        migrations.AddIndex(
            model_name='unregisteredap',
            index=models.Index(fields=['bssid'], name='evidence_un_bssid_2a5906_idx'),
        ),
        migrations.AddIndex(
            model_name='unregisteredap',
            index=models.Index(fields=['ssid'], name='evidence_un_ssid_1cbb9a_idx'),
        ),
        migrations.AddIndex(
            model_name='unregisteredap',
            index=models.Index(fields=['is_active'], name='evidence_un_is_acti_a6b959_idx'),
        ),
    ]
