# Generated by Django 5.0.6 on 2025-10-30 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.CharField(max_length=64)),
                ('bssid', models.CharField(max_length=17)),
                ('rsn', models.JSONField(blank=True, null=True)),
                ('rssi', models.IntegerField(blank=True, null=True)),
                ('sensor_ts', models.DateTimeField()),
                ('server_ts', models.DateTimeField(auto_now_add=True)),
                ('payload_hash', models.BinaryField()),
                ('prev_chain_hash', models.BinaryField(blank=True, null=True)),
                ('chain_hash', models.BinaryField()),
                ('device_sig', models.BinaryField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.device')),
            ],
            options={
                'indexes': [models.Index(fields=['ssid', 'bssid', 'server_ts'], name='evidence_ob_ssid_bef52c_idx')],
            },
        ),
    ]
