# Generated by Django 5.2.7 on 2025-11-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesspointobservation',
            name='flags',
            field=models.JSONField(default=list, help_text="List of triggered alert flags, e.g. ['UNREGISTERED_AP']"),
        ),
        migrations.AlterField(
            model_name='accesspointobservation',
            name='risk_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='accesspointobservation',
            name='similarity_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='accesspointwhitelistentry',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to disable this exact AP entry without deleting it.'),
        ),
        migrations.AlterField(
            model_name='accesspointwhitelistgroup',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to temporarily disable this whitelist group (all its entries will be ignored in matching).'),
        ),
        migrations.AddIndex(
            model_name='accesspointwhitelistentry',
            index=models.Index(fields=['bssid'], name='evidence_ac_bssid_6690d4_idx'),
        ),
        migrations.AddIndex(
            model_name='accesspointwhitelistentry',
            index=models.Index(fields=['is_active'], name='evidence_ac_is_acti_c6747e_idx'),
        ),
        migrations.AddIndex(
            model_name='accesspointwhitelistgroup',
            index=models.Index(fields=['ssid'], name='evidence_ac_ssid_3b475c_idx'),
        ),
        migrations.AddIndex(
            model_name='accesspointwhitelistgroup',
            index=models.Index(fields=['is_active'], name='evidence_ac_is_acti_89a5cd_idx'),
        ),
    ]
