# Generated by Django 5.2.7 on 2025-11-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspointobservation',
            name='chain_hash',
            field=models.BinaryField(blank=True, help_text='Hash linking previous chain to this observation', null=True),
        ),
        migrations.AddField(
            model_name='accesspointobservation',
            name='integrity_ok',
            field=models.BooleanField(default=True, help_text='Set False if later verification fails'),
        ),
        migrations.AddField(
            model_name='accesspointobservation',
            name='prev_chain_hash',
            field=models.BinaryField(blank=True, help_text='Hash of previous observation for this device', null=True),
        ),
    ]
