# Generated by Django 5.2.7 on 2025-11-14 18:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('evidence', '0002_accesspointobservation_chain_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesspointobservation',
            name='match_status',
            field=models.CharField(blank=True, help_text='Snapshot status at ingest, e.g.: WHITELISTED_STRONG / WHITELISTED_WEAK / CHANNEL_MISMATCH / SECURITY_MISMATCH / KNOWN_SSID_BUT_UNEXPECTED_AP / KNOWN_SSID_REJECTED / UNREGISTERED_AP', max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='UnregisteredAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.CharField(blank=True, max_length=64)),
                ('bssid', models.CharField(blank=True, db_index=True, help_text='AP MAC if known, otherwise empty for SSID-only entries.', max_length=17)),
                ('oui', models.CharField(blank=True, help_text="First 3 bytes of BSSID, as hex (e.g. 'F09FC2').", max_length=8)),
                ('channel', models.IntegerField(blank=True, help_text='Most recently seen channel for this AP.', null=True)),
                ('first_seen', models.DateTimeField(help_text='When this unregistered AP was first seen.')),
                ('last_seen', models.DateTimeField(help_text='When this unregistered AP was last seen.')),
                ('seen_count', models.PositiveIntegerField(default=0, help_text="How many times we've seen it.")),
                ('is_active', models.BooleanField(default=True, help_text='Active = still of interest; False = acknowledged / suppressed.')),
                ('notes', models.TextField(blank=True, help_text='Operator notes / investigation outcome.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_device', models.ForeignKey(blank=True, help_text='Last device that saw this AP.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unregistered_aps_last_seen', to='devices.device')),
            ],
            options={
                'verbose_name': 'Unregistered AP',
                'verbose_name_plural': 'Unregistered APs',
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['bssid'], name='evidence_un_bssid_2a5906_idx'), models.Index(fields=['ssid'], name='evidence_un_ssid_1cbb9a_idx'), models.Index(fields=['is_active'], name='evidence_un_is_acti_a6b959_idx')],
            },
        ),
    ]
