# Generated by Django 5.2.7 on 2025-10-31 08:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_append_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPointWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.CharField(db_index=True, max_length=64)),
                ('bssid', models.CharField(blank=True, db_index=True, help_text='MAC address of the AP (optional if SSID-based trust only)', max_length=17, null=True)),
                ('vendor_oui', models.CharField(blank=True, help_text='OUI prefix, e.g. F0:9F:C2', max_length=8, null=True)),
                ('expected_security', models.CharField(blank=True, help_text='Expected security type, e.g. WPA2-PSK', max_length=64, null=True)),
                ('allowed_bands', models.CharField(blank=True, help_text="Comma-separated, e.g. '2.4GHz,5GHz,6GHz'", max_length=32, null=True)),
                ('allowed_channels', models.CharField(blank=True, help_text="Comma-separated channel list, e.g. '1,6,11'", max_length=128, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Access Point Whitelist',
                'verbose_name_plural': 'Access Point Whitelist',
                'unique_together': {('ssid', 'bssid')},
            },
        ),
        migrations.CreateModel(
            name='AccessPointObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.CharField(blank=True, max_length=64, null=True)),
                ('bssid', models.CharField(db_index=True, max_length=17)),
                ('channel', models.PositiveIntegerField(default=1, help_text='Wi-Fi channel (1–196)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(196)])),
                ('band', models.CharField(blank=True, help_text='e.g. 2.4GHz / 5GHz / 6GHz', max_length=16, null=True)),
                ('security', models.CharField(blank=True, help_text='Security type detected', max_length=64, null=True)),
                ('rssi', models.IntegerField(blank=True, help_text='Signal strength (dBm)', null=True)),
                ('vendor_oui', models.CharField(blank=True, max_length=8, null=True)),
                ('location_hint', models.CharField(blank=True, max_length=128, null=True)),
                ('source_device', models.CharField(blank=True, help_text='Identifier of scanning device', max_length=64, null=True)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_whitelisted', models.BooleanField(default=False)),
                ('similarity_score', models.FloatField(default=0.0, help_text='0–1 similarity to whitelist SSID')),
                ('risk_score', models.FloatField(default=0.0, help_text='0–100 computed risk score')),
                ('flags', models.JSONField(default=list, help_text='List of triggered alert flags')),
                ('is_flagged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched_whitelist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='evidence.accesspointwhitelist')),
            ],
            options={
                'verbose_name': 'Access Point Observation',
                'verbose_name_plural': 'Access Point Observations',
            },
        ),
        migrations.DeleteModel(
            name='Observation',
        ),
        migrations.AddIndex(
            model_name='accesspointobservation',
            index=models.Index(fields=['ssid'], name='evidence_ac_ssid_5105fe_idx'),
        ),
        migrations.AddIndex(
            model_name='accesspointobservation',
            index=models.Index(fields=['bssid'], name='evidence_ac_bssid_18c5e6_idx'),
        ),
    ]
