# Generated by Django 5.2.7 on 2025-10-31 08:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_device_is_active'),
        ('evidence', '0003_accesspointwhitelist_accesspointobservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspointobservation',
            name='chain_hash',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accesspointobservation',
            name='device',
            field=models.ForeignKey(blank=True, help_text='Originating scanner / device', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ap_observations', to='devices.device'),
        ),
        migrations.AddField(
            model_name='accesspointobservation',
            name='payload_hash',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accesspointobservation',
            name='prev_chain_hash',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accesspointobservation',
            name='sensor_ts',
            field=models.DateTimeField(blank=True, help_text='Device-reported timestamp (UTC)', null=True),
        ),
        migrations.AddField(
            model_name='accesspointobservation',
            name='server_ts',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Server ingest timestamp'),
        ),
        migrations.AddIndex(
            model_name='accesspointobservation',
            index=models.Index(fields=['server_ts'], name='evidence_ac_server__30f17b_idx'),
        ),
        migrations.AddIndex(
            model_name='accesspointobservation',
            index=models.Index(fields=['device'], name='evidence_ac_device__412ebb_idx'),
        ),
    ]
